#!/usr/bin/env python3
from pathlib import Path
import gzip
import hashlib
import hmac
import re
import struct
import zlib
from collections.abc import Mapping
from typing import Final


ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / "web"
ASSET_DIGEST_HEADER: Final = ROOT.parent / "applications_user" / "pocket_airbridge" / "airbridge_assets_digest.h"
BUNDLE_MAGIC: Final = b"ABND"
BUNDLE_FORMAT_VERSION: Final = 1
BUNDLE_HEADER: Final = struct.Struct("<4sB3xI")
BOOTSTRAPS = (
    (WEB / "bootstrap.js", 1200),
)
BUNDLES = (
    ("chat-usb.html", "app-usb.html", "WebHIDAdapter"),
)
PROTOCOL_IMPORT = (
    "import { AirBridgeCryptoSession, buildMessage, CRYPTO_ROLE, CRYPTO_STATE, encodeMeta, ItemReceiver, ItemSender, MAX_PAYLOAD, MSG, "
    "parseMessage, sha256 } from './airbridge-protocol.js';"
)
PROTOCOL_BINDINGS = [
    "AirBridgeCryptoSession",
    "buildMessage",
    "CRYPTO_ROLE",
    "CRYPTO_STATE",
    "encodeMeta",
    "ItemReceiver",
    "ItemSender",
    "MAX_PAYLOAD",
    "MSG",
    "parseMessage",
    "sha256",
]
EVIDENCE_IMPORT = (
    "import { createTimingRecorder, recordCancel, recordFlipperCounters } from './airbridge-evidence.js';"
)
EVIDENCE_BINDINGS = [
    "createTimingRecorder",
    "recordCancel",
    "recordFlipperCounters",
]
UI_CSS_LINK = '<link rel="stylesheet" href="./airbridge-ui.css">'
UI_IMPORT_RE = re.compile(
    r"(?m)^import \{ (?P<bindings>[^}]+) \} from './airbridge-ui\.js';$"
)


class BundleFormatError(ValueError):
    pass


class BundleBuildError(ValueError):
    pass


def inline_module(path: Path, bindings: list[str] | None) -> str:
    source = path.read_text(encoding="utf-8")
    source = re.sub(r"(?ms)^\s*import\s+.*?;\s*\n?", "", source)
    source = re.sub(r"(?m)^(\s*)export\s+", r"\1", source)
    if bindings is None:
        return source
    names = ", ".join(bindings)
    return f"const {{ {names} }} = (() => {{\n{source}\nreturn {{ {names} }};\n}})();"


def replace_once(page: str, needle: str, replacement: str) -> str:
    if page.count(needle) != 1:
        raise BundleBuildError(f"expected exactly one {needle!r} in chat-usb.html")
    return page.replace(needle, replacement)


def inline_ui_css(page: str) -> str:
    css = (WEB / "airbridge-ui.css").read_text(encoding="utf-8")
    return replace_once(page, UI_CSS_LINK, f"<style>\n{css}\n</style>")


def inline_ui_module(page: str) -> str:
    matches = list(UI_IMPORT_RE.finditer(page))
    if len(matches) != 1:
        raise BundleBuildError("expected exactly one airbridge-ui.js import line")
    bindings = [part.strip() for part in matches[0].group("bindings").split(",") if part.strip()]
    if not bindings:
        raise BundleBuildError("expected at least one UI binding")
    return page[: matches[0].start()] + inline_module(WEB / "airbridge-ui.js", bindings) + page[matches[0].end() :]


def gzip_deterministic(data: bytes) -> bytes:
    compressed = bytearray(gzip.compress(data, compresslevel=9, mtime=0))
    compressed[9] = 0xFF
    return bytes(compressed)


def asset_digest_matches(data: bytes, expected: bytes) -> bool:
    return hmac.compare_digest(hashlib.sha256(data).digest(), expected)


def build_bundle_container(raw: bytes) -> bytes:
    compressed = gzip_deterministic(raw)
    return BUNDLE_HEADER.pack(BUNDLE_MAGIC, BUNDLE_FORMAT_VERSION, len(raw)) + compressed


def decode_bundle_container(container: bytes) -> bytes:
    if len(container) < BUNDLE_HEADER.size + 2:
        raise BundleFormatError("bundle container is truncated")
    magic, version, decompressed_size = BUNDLE_HEADER.unpack_from(container)
    if magic != BUNDLE_MAGIC:
        raise BundleFormatError("bundle magic mismatch")
    if version != BUNDLE_FORMAT_VERSION:
        raise BundleFormatError("bundle format version mismatch")
    compressed = container[BUNDLE_HEADER.size :]
    if compressed[:2] != b"\x1f\x8b":
        raise BundleFormatError("bundle gzip magic mismatch")
    try:
        raw = gzip.decompress(compressed)
    except (gzip.BadGzipFile, EOFError, zlib.error) as error:
        raise BundleFormatError("bundle gzip payload is invalid") from error
    if len(raw) != decompressed_size:
        raise BundleFormatError("bundle decompressed size mismatch")
    return raw


def _c_bytes(data: bytes) -> str:
    return ", ".join(f"0x{value:02X}" for value in data)


def render_digest_header(bootstrap: bytes, bundles: Mapping[str, bytes]) -> str:
    app_usb = bundles["app-usb.html"]
    container = build_bundle_container(app_usb)
    return "\n".join(
        (
            "/* Generated by airbridge/tools/build_bundle.py; do not edit. */",
            "#pragma once",
            "",
            "#include <stddef.h>",
            "#include <stdint.h>",
            "",
            f"#define AIRBRIDGE_BUNDLE_FORMAT_VERSION {BUNDLE_FORMAT_VERSION}U",
            f"#define AIRBRIDGE_BUNDLE_HEADER_SIZE {BUNDLE_HEADER.size}U",
            "#define AIRBRIDGE_ASSET_SHA256_SIZE 32U",
            f"#define AIRBRIDGE_APP_USB_DECOMPRESSED_SIZE {len(app_usb)}U",
            "",
            f"static const uint8_t AIRBRIDGE_BUNDLE_MAGIC[{len(BUNDLE_MAGIC)}] = {{{_c_bytes(BUNDLE_MAGIC)}}};",
            f"static const uint8_t AIRBRIDGE_BOOTSTRAP_SHA256[32] = {{{_c_bytes(hashlib.sha256(bootstrap).digest())}}};",
            f"static const uint8_t AIRBRIDGE_APP_USB_BUNDLE_SHA256[32] = {{{_c_bytes(hashlib.sha256(container).digest())}}};",
            "",
        )
    )


def normalize_bootstrap(data: bytes, path: Path) -> bytes:
    normalized = data.replace(b"\r\n", b"\n").replace(b"\r", b"\n").rstrip(b"\n")
    for offset, value in enumerate(normalized):
        if value < 0x20 or value > 0x7E:
            char = chr(value) if value < 0x80 else f"\\x{value:02x}"
            message = f"{path.relative_to(ROOT)} contains non-US-ASCII byte "
            message += f"0x{value:02X} ({char!r}) at offset {offset}"
            raise BundleBuildError(message)
    return normalized


def build_bundle() -> dict[str, bytes]:
    """Build all bundles in memory, returning {output_name: raw_bytes}."""
    bundles: dict[str, bytes] = {}
    for page_name, output_name, adapter_name in BUNDLES:
        page = (WEB / page_name).read_text(encoding="utf-8")
        page = inline_ui_css(page)
        page = inline_ui_module(page)
        page = replace_once(
            page,
            PROTOCOL_IMPORT,
            inline_module(WEB / "airbridge-protocol.js", PROTOCOL_BINDINGS),
        )
        page = replace_once(
            page,
            EVIDENCE_IMPORT,
            inline_module(WEB / "airbridge-evidence.js", EVIDENCE_BINDINGS),
        )
        page = replace_once(
            page,
            f"import {{ {adapter_name} }} from './airbridge-transports.js';",
            "\n".join(
                (
                    inline_module(WEB / "airbridge-identity.js", None),
                    inline_module(WEB / "airbridge-transports.js", [adapter_name]),
                ),
            ),
        )
        page = replace_once(page, '<script type="module">', "<script>")
        if 'href="./airbridge-ui.css"' in page:
            raise BundleBuildError("bundle still contains UI stylesheet link")
        if "from './airbridge-ui.js'" in page:
            raise BundleBuildError("bundle still contains UI module import")
        if "import " in page or 'type="module"' in page:
            raise BundleBuildError("bundle still contains module syntax")
        bundles[output_name] = page.encode("utf-8")
    return bundles


def bundle_matches_source() -> bool:
    """True when deploy assets and generated digest metadata are fresh."""
    output_dir = ROOT / "dist"
    bundles = build_bundle()
    for name, raw in bundles.items():
        on_disk = (output_dir / name).read_bytes()
        if on_disk != raw:
            return False
        on_disk_bundle = (output_dir / (name + ".gz")).read_bytes()
        if on_disk_bundle != build_bundle_container(raw):
            return False
    bootstrap_path = WEB / "bootstrap.js"
    bootstrap = normalize_bootstrap(bootstrap_path.read_bytes(), bootstrap_path)
    return ASSET_DIGEST_HEADER.read_text(encoding="utf-8") == render_digest_header(bootstrap, bundles)


def main() -> None:
    normalized_bootstraps: dict[Path, bytes] = {}
    for bootstrap_path, max_chars in BOOTSTRAPS:
        bootstrap = normalize_bootstrap(bootstrap_path.read_bytes(), bootstrap_path)
        if len(bootstrap) > max_chars:
            message = f"{bootstrap_path.relative_to(ROOT)} exceeds {max_chars} chars: "
            message += str(len(bootstrap))
            raise BundleBuildError(message)
        if bootstrap != bootstrap_path.read_bytes():
            _ = bootstrap_path.write_bytes(bootstrap)
        normalized_bootstraps[bootstrap_path] = bootstrap
        print(
            f"{bootstrap_path.relative_to(ROOT)}: {len(bootstrap)} chars, "
            f"sha256={hashlib.sha256(bootstrap).hexdigest()}"
        )

    output_dir = ROOT / "dist"
    output_dir.mkdir(parents=True, exist_ok=True)
    bundles = build_bundle()
    for output_name, raw in bundles.items():
        output = output_dir / output_name
        _ = output.write_bytes(raw)
        compressed = build_bundle_container(raw)
        compressed_output = output.with_suffix(output.suffix + ".gz")
        _ = compressed_output.write_bytes(compressed)
        if len(compressed) >= len(raw):
            raise BundleBuildError(f"{compressed_output.relative_to(ROOT)} is not smaller than {output.relative_to(ROOT)}")
        print(
            "".join(
                (
                    f"{output.relative_to(ROOT)}: {len(raw)} bytes, ",
                    f"{compressed_output.relative_to(ROOT)}: {len(compressed)} bytes, ",
                    f"sha256={hashlib.sha256(raw).hexdigest()}, ",
                    f"bundle_sha256={hashlib.sha256(compressed).hexdigest()}",
                )
            )
        )

    header = render_digest_header(normalized_bootstraps[WEB / "bootstrap.js"], bundles)
    _ = ASSET_DIGEST_HEADER.write_text(header, encoding="utf-8")
    print(f"{ASSET_DIGEST_HEADER.relative_to(ROOT.parent)}: generated")


if __name__ == "__main__":
    _ = main()
